-- =========================================================================
-- flockkeeper DATABASE SCHEMA INITIALIZATION
-- =========================================================================

-- 1. ANIMALS TABLE
CREATE TABLE IF NOT EXISTS public.animals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    barn_name TEXT,
    nkr_reg_number TEXT,
    tattoo TEXT,
    ear_tag TEXT,
    rfid_tag TEXT,
    dob TEXT,
    sex TEXT NOT NULL,
    color TEXT,
    markings TEXT,
    registry TEXT,
    breed_type TEXT,
    herd_book TEXT,
    vgl_id TEXT,
    eid_type TEXT,
    eid_placement TEXT,
    id_tag_number TEXT,
    id_tag_placement TEXT,
    scrapie_tag TEXT,
    eye_color TEXT,
    ear_type TEXT,
    horn_type TEXT,
    description TEXT,
    ownership_status TEXT,
    breed TEXT DEFAULT 'Kiko',
    dam_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    sire_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    dam_name TEXT,
    sire_name TEXT,
    dam_reg_number TEXT,
    sire_reg_number TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    birth_weight_lbs DOUBLE PRECISION,
    purchase_date TEXT,
    purchase_price DOUBLE PRECISION,
    sold_date TEXT,
    sold_price DOUBLE PRECISION,
    sold_to TEXT,
    deceased_date TEXT,
    deceased_reason TEXT,
    photo_path TEXT,
    notes TEXT,
    is_herd_sire INTEGER NOT NULL DEFAULT 0,
    is_registered INTEGER NOT NULL DEFAULT 0,
    second_registry TEXT,
    second_reg_number TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. WEIGHT RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.weight_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    weigh_date TEXT NOT NULL,
    weight_lbs DOUBLE PRECISION NOT NULL,
    body_condition_score INTEGER,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. BREEDING EVENTS TABLE
CREATE TABLE IF NOT EXISTS public.breeding_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    buck_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    doe_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    buck_name TEXT,
    doe_name TEXT,
    breeding_date TEXT NOT NULL,
    expected_kid_date TEXT,
    actual_kid_date TEXT,
    method TEXT DEFAULT 'natural',
    confirmed_pregnant INTEGER NOT NULL DEFAULT 0,
    confirmation_date TEXT,
    confirmation_method TEXT,
    outcome TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. KIDDING RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.kidding_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    breeding_event_id BIGINT REFERENCES public.breeding_events(id) ON DELETE SET NULL,
    doe_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    buck_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    kid_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    kid_name TEXT,
    kidding_date TEXT NOT NULL,
    birth_order INTEGER,
    litter_size INTEGER,
    birth_weight_lbs DOUBLE PRECISION,
    sex TEXT,
    birth_type TEXT,
    presentation TEXT,
    survival_status TEXT DEFAULT 'alive',
    received_colostrum INTEGER DEFAULT 0,
    bottle_fed INTEGER DEFAULT 0,
    dam_condition_score INTEGER,
    complications TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. HEALTH RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.health_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    record_date TEXT NOT NULL,
    record_type TEXT NOT NULL,
    diagnosis TEXT,
    treatment TEXT,
    dosage TEXT,
    administrator TEXT,
    famacha_score INTEGER,
    bcs_score DOUBLE PRECISION,
    withdrawal_days INTEGER,
    withdrawal_date TEXT,
    lab_name TEXT,
    lab_reference_number TEXT,
    follow_up_date TEXT,
    cost DOUBLE PRECISION,
    resolved INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6. PASTURES TABLE
CREATE TABLE IF NOT EXISTS public.pastures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    acreage DOUBLE PRECISION,
    description TEXT,
    forage_type TEXT,
    water_source TEXT,
    fencing_type TEXT,
    carrying_capacity INTEGER,
    current_animal_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'available',
    last_grazed_date TEXT,
    available_date TEXT,
    rest_days_target INTEGER DEFAULT 30,
    notes TEXT,
    boundary_polygon TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. PASTURE HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.pasture_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    pasture_id BIGINT NOT NULL REFERENCES public.pastures(id) ON DELETE CASCADE,
    animal_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    group_name TEXT,
    move_in_date TEXT NOT NULL,
    move_out_date TEXT,
    animal_count INTEGER,
    forage_condition_in TEXT,
    forage_condition_out TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 8. VACCINATIONS TABLE
CREATE TABLE IF NOT EXISTS public.vaccinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    vaccine_name TEXT NOT NULL,
    vaccine_type TEXT,
    given_date TEXT NOT NULL,
    next_due_date TEXT,
    lot_number TEXT,
    manufacturer TEXT,
    dosage_ml DOUBLE PRECISION,
    administered_by TEXT,
    injection_site TEXT,
    cost DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 9. DEWORMINGS TABLE
CREATE TABLE IF NOT EXISTS public.dewormings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT NOT NULL REFERENCES public.animals(id) ON DELETE CASCADE,
    deworming_date TEXT NOT NULL,
    famacha_score INTEGER,
    fec_count DOUBLE PRECISION,
    product_name TEXT,
    active_ingredient TEXT,
    dosage_ml DOUBLE PRECISION,
    weight_at_time_lbs DOUBLE PRECISION,
    withdrawal_days INTEGER,
    withdrawal_date TEXT,
    administered_by TEXT,
    cost DOUBLE PRECISION,
    next_check_date TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 10. FINANCIAL RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.financial_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT REFERENCES public.animals(id) ON DELETE SET NULL,
    record_date TEXT NOT NULL,
    category TEXT NOT NULL,
    type TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    description TEXT,
    vendor_buyer TEXT,
    receipt_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 11. REMINDERS TABLE
CREATE TABLE IF NOT EXISTS public.reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT REFERENCES public.animals(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    reminder_date TEXT NOT NULL,
    reminder_type TEXT,
    is_completed INTEGER NOT NULL DEFAULT 0,
    completed_date TEXT,
    is_recurring INTEGER NOT NULL DEFAULT 0,
    recurrence_days INTEGER,
    notify_days_before INTEGER DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 12. NOTES TABLE
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    animal_id BIGINT REFERENCES public.animals(id) ON DELETE CASCADE,
    pasture_id BIGINT REFERENCES public.pastures(id) ON DELETE CASCADE,
    note_date TEXT NOT NULL,
    title TEXT,
    body TEXT NOT NULL,
    category TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 13. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, key)
);

-- 14. DELETED RECORDS TABLE
CREATE TABLE IF NOT EXISTS public.deleted_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    table_name TEXT NOT NULL,
    record_id BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_table_record_user UNIQUE (table_name, record_id, user_id)
);


-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

-- Enable RLS for all created tables
ALTER TABLE public.animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.breeding_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kidding_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pastures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pasture_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vaccinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dewormings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deleted_records ENABLE ROW LEVEL SECURITY;

-- Setup policy rules (User-specific isolation based on auth.uid() = user_id)
CREATE POLICY "Users can manage their own animals" ON public.animals FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own weight records" ON public.weight_records FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own breeding events" ON public.breeding_events FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own kidding records" ON public.kidding_records FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own health records" ON public.health_records FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own pastures" ON public.pastures FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own pasture history" ON public.pasture_history FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own vaccinations" ON public.vaccinations FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own dewormings" ON public.dewormings FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own financial records" ON public.financial_records FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own reminders" ON public.reminders FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own notes" ON public.notes FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own settings" ON public.settings FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can manage their own deleted records" ON public.deleted_records FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());


-- =========================================================================
-- STORAGE BUCKET CONFIGURATION
-- =========================================================================

-- Create a storage bucket called "flockkeeper"
INSERT INTO storage.buckets (id, name, public)
VALUES ('flockkeeper', 'flockkeeper', false)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on storage.objects
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Grant access policy for the storage bucket
-- Enforces that users can only upload/access objects under their own UUID prefix folder: e.g. "auth.uid()/photos/..."
CREATE POLICY "Users can manage their own files in flockkeeper bucket"
ON storage.objects
FOR ALL
TO authenticated
USING (
    bucket_id = 'flockkeeper' 
    AND (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
    bucket_id = 'flockkeeper' 
    AND (storage.foldername(name))[1] = auth.uid()::text
);
